version: '3'
services:

  reverse-proxy:
    image: traefik
    command: --api --docker --loglevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:8080"
    labels:
      - "traefik.port=9000"
      - "traefik.frontend.rule=Path:/visualizer"
      #- "traefik.backend=visualizer"
