version: '3'
services:

  proxy:
    image: traefik
    command:
      - --logLevel=INFO
      - --api
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --docker
      - --docker.watch
      - --acme
      - --acme.onHostRule
      - --acme.storage=/acme.json
      - --acme.email=jpsecher@gmail.com
      - --acme.entryPoint=https
      - --acme.domains=test.kaleidoscope.software
      - --acme.httpChallenge.entryPoint=http
      - --acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
    restart: always

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.frontend.rule=Path:/whoami"

  counter:
    image: jpsecher/ip-and-counter
    labels:
      - "traefik.frontend.rule=Path:/counter"
