version: '3'
services:

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    restart: always

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.frontend.rule=Path:/whoami"

  counter:
    image: jpsecher/ip-and-counter
    labels:
      - "traefik.frontend.rule=Path:/counter"
